import { pgTable, text, timestamp, jsonb, boolean, integer } from "drizzle-orm/pg-core";

export const siteIdentity = pgTable("site_identity", {
  id: integer("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  keywords: text("keywords").notNull(),
  author: text("author").notNull(),
  address: text("address").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  googleMapsUrl: text("google_maps_url"),
  imageMapUrl: text("image_map_url"),
  defaultLang: text("default_lang").notNull(),
  siteUrl: text("site_url").notNull(),
  defaultOgImage: text("default_og_image"),
  defaultCanonicalUrl: text("default_canonical_url"),
  logoUrl: text("logo_url"),
  logoAlt: text("logo_alt"),
  logoSizes: jsonb("logo_sizes"),
  favicon: text("favicon"),
  robotsContent: text("robots_content"),
  themeColor: text("theme_color"),
  ctaLabel: text("cta_label"),
  ctaUrl: text("cta_url"),
  devName: text("dev_name"),
  devUrl: text("dev_url"),
  devEmail: text("dev_email"),
  hostName: text("host_name"),
  hostAddress: text("host_address"),
  hostUrl: text("host_url"),
  hostContact: text("host_contact"),
  mediatorName: text("mediator_name"),
  mediatorAddress: text("mediator_address"),
  mediatorUrl: text("mediator_url"),
  mediatorContact: text("mediator_contact"),
  footerText: text("footer_text"),
  socialLinks: jsonb("social_links"),
  navLinks: jsonb("nav_links"),
  navSecondaryLinks: jsonb("nav_secondary_links"),
  stats: jsonb("stats"),
  isDefault: boolean("is_default").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});